# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: HOME
    url: "#hero"
    weight: 10
  - name: PACKAGES
    url: "#packages"
    weight: 20
  - name: TEAM
    url: "#team"
    weight: 30
  - name: CONTACT
    url: "#contact"
    weight: 40
  - name: CONTRIBUTION
    url: "#contribution"
    weight: 50
  - name: DATABASES
    url: databases/
    weight: 51
  - name: TUTORIAL
    identifier: tutorial
    url: docs/
    weight: 60
  - name: R packages (old version)
    parent: tutorial
    url: docs/
    weight: 61
  - name: R packages (new version)
    parent: tutorial
    url: https://www.tidymass.org/tidymass-tutorial/
    weight: 62
  - name: tidymass shiny
    parent: tutorial
    url: https://www.tidymass.org/tidymassshiny-tutorial/
    weight: 63
  - name: NEWS
    url: news/
    weight: 70    
