---
date: "2025-05-06T00:00:00+01:00"
title: "TidyMass Shiny Application"
linktitle: TidyMass Shiny Application
author: admin
type: book
weight: 1
commentable: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = TRUE,
  out.width = "100%"
)
knitr::opts_knit$set(root.dir = here::here("content/docs"))
```

If you haven't installed `TidyMass` yet, please install it according to [the installation instructions](https://www.tidymass.org/docs/chapter1/1-installation/).

Install the necessary packages:

```{r, echo=TRUE, eval=FALSE}
if (!require('remotes')) install.packages('remotes');
if (!require('tidyverse')) install.packages('tidyverse');
if (!require('writexl')) install.packages("writexl");
if (!require('hexbin')) install.packages('hexbin')
if (!require('ComplexUpset'))install.packages('ComplexUpset');
if (!require('shinyalert'))install.packages('shinyalert');
if (!require('shinyFiles')) remotes::install_github('thomasp85/shinyFiles');
if (!require('shinyWidgets')) remotes::install_github("dreamRs/shinyWidgets");
if (!require('shiny')) install.packages('shiny');
if (!require('bsicons')) install.packages('bsicons');
if (!require('bslib')) install.packages('bslib');
if (!require('plotly')) install.packages('plotly');
if (!require('colourpicker')) install.packages('colourpicker');
if (!require('massdbbuildin')) remotes::install_github('tidymass/massdbbuildin')
```

Then install Tidymass shinyapp with the code:

```{r, echo=TRUE, eval=FALSE}
remotes::install_github('tidymass/tidymass_shiny')
```

To start the Tidymass shinyapp:

```{r, echo=TRUE, eval=FALSE}
library(tidyverse)
library(tidymass)
library(tidymassshiny)
run_tidymass_shiny()
```

The completerd tutorials of TidyMassShiny can be found here: [https://www.tidymass.org/tidymassshiny-tutorial/](https://www.tidymass.org/tidymassshiny-tutorial/)

## Session information

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
sessionInfo()
```
